### PR TITLE
Import gcd from math instead of fractions for Python 3.9 compatibility.

### LINKED ISSUE #6: Error on "from fractions import gcd"
On Python 3.9 I obtain an error on "from fractions import gcd". Changing the line in `thinkdsp.py` to "from math import gcd" makes to package work.

### PR DESCRIPTION
**Pull request by tirkarthi**
Fixes #6

### CODE REVIEW

**Review by lockepatton — APPROVED** [review]
Thanks @tirkarthi !

**Comment by BakiaGlilit** [comment]
I'm using Pycharm and in order to install thinkdsp I used the pip command "pip install thinkx". I ran the following code 
`import thinkdsp
from math import gcd

cos_sig = thinkdsp.CosSignal(freq=440, amp=1.0, offset=0)
sin_sig = thinkdsp.SinSignal(freq=880, amp=0.5, offset=0)`

and got the error
`ImportError: cannot import name 'gcd' from 'fractions'`

I understand I need to import gcd from math, but how should I do that in a way that thinkdsp will work for me?

**Comment by lockepatton** [comment]
Did you ever solve this @BakiaGlilit? My first guess has to do with the location of thinkdsp. With their permission, their code is replicated in our code, so you should be able to uninstall thinkx through pip, and it should work. Let me know if that solves your issue, if its still an open issue for you.

**Review by lockepatton — COMMENTED** [review]
Thanks.

**Pull request merged**
